//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BallBotGui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1001912154644")]
        public string chatId {
            get {
                return ((string)(this["chatId"]));
            }
            set {
                this["chatId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Волейбол в ЗАЛЕ с 8 до 10 вечера.")]
        public string pollQuestion {
            get {
                return ((string)(this["pollQuestion"]));
            }
            set {
                this["pollQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Вторник. 20.00-22.00")]
        public string questTuesday {
            get {
                return ((string)(this["questTuesday"]));
            }
            set {
                this["questTuesday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Четверг 20.00-22.00")]
        public string questThursday {
            get {
                return ((string)(this["questThursday"]));
            }
            set {
                this["questThursday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Воскресенье 20.00-22.00")]
        public string questSunday {
            get {
                return ((string)(this["questSunday"]));
            }
            set {
                this["questSunday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Пропускаю. Но очень хочу играть.")]
        public string questSkip {
            get {
                return ((string)(this["questSkip"]));
            }
            set {
                this["questSkip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int pollDay {
            get {
                return ((int)(this["pollDay"]));
            }
            set {
                this["pollDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int pollHour {
            get {
                return ((int)(this["pollHour"]));
            }
            set {
                this["pollHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Играю!")]
        public string mainQuestion {
            get {
                return ((string)(this["mainQuestion"]));
            }
            set {
                this["mainQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1001645946649")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-912842250")]
        public string Setting1 {
            get {
                return ((string)(this["Setting1"]));
            }
            set {
                this["Setting1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5,6,2,4")]
        public string pollDayList {
            get {
                return ((string)(this["pollDayList"]));
            }
            set {
                this["pollDayList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int pollBeforeGame {
            get {
                return ((int)(this["pollBeforeGame"]));
            }
            set {
                this["pollBeforeGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{dayName} 19.00-21.00")]
        public string pollTitleTemplate {
            get {
                return ((string)(this["pollTitleTemplate"]));
            }
            set {
                this["pollTitleTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7109057711:AAExaDyyO7pGpFAio9LmyVprOO67Om2jcDo")]
        public string curBotKey {
            get {
                return ((string)(this["curBotKey"]));
            }
            set {
                this["curBotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Приветствуем, @Player!\r\n - Мы вам рады!\r\n - Ответы на вопросы Где? Когда? Как зап" +
            "исаться? тут: https://t.me/c/1645946649/4774\r\n - Обязательно напишите о своем ур" +
            "овне игры.\r\n - Все текущие игры в закрепах")]
        public string inviteMessage {
            get {
                return ((string)(this["inviteMessage"]));
            }
            set {
                this["inviteMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Двигайся к цели! Даже маленький шаг сегодня – это большой результат завтра!|Твое " +
            "будущее тело зависит от того, что ты делаешь сегодня!|Лень пройдет, а гордость з" +
            "а себя останется!|Час тренировки – всего 4% твоего дня. Ты точно не найдешь врем" +
            "я?|Преодолей себя, и ты станешь сильнее во всем!|После тренировки ты будешь чувс" +
            "твовать себя лучше, чем сейчас. Проверь!|Сегодня ты можешь стать сильнее, чем бы" +
            "л вчера. Не упускай шанс!|Тело создано для движения. Не лишай его этого!|Начни п" +
            "рямо сейчас, и уже через месяц ты скажешь себе \'Спасибо\'!|Ты не должен быть лучш" +
            "им. Ты должен быть лучше, чем вчера!|Спорт – это инвестиция в себя, которая всег" +
            "да окупается!|Пот сегодня – гордость завтра!|Никто не сделает это за тебя. Но ты" +
            " можешь сделать это для себя!|Ты сильнее, чем твои оправдания. Действуй!|Болит? " +
            "Значит, ты работаешь над собой! Не сдавайся!|Одна тренировка не сделает тебя чем" +
            "пионом, но без нее ты им точно не станешь!|Результат не придет сразу, но каждый " +
            "шаг приближает тебя к нему!|Сделай первый шаг, а дальше появится энергия двигать" +
            "ся вперед!|Тренировка – лучший способ перезагрузить голову и тело!|Не думай. Про" +
            "сто вставай и делай!|Каждый повтор – это шаг к силе!|Хочешь красивое тело? Тогда" +
            " начни прямо сейчас!|День без движения – шаг назад!|Вложи энергию в спорт, и он " +
            "вложит её в тебя!|Тренировка – это лучшее лекарство от стресса!|Ты можешь больше" +
            ", чем думаешь! Проверь себя!|Нет идеального времени для начала, но есть идеально" +
            "е тело после тренировок!|Преодолей лень – и ты уже победил!|Никто не станет силь" +
            "нее за тебя! Действуй!|Кто-то мечтает о форме, а кто-то идёт и делает её!|Сильно" +
            "е тело – сильный дух!|Привычка к спорту – привычка к успеху!|Нужно всего 21 день" +
            ", чтобы сделать спорт своей привычкой!|Ты один раз решишь потренироваться – и да" +
            "льше это станет легче!|Каждое движение приближает тебя к мечте!|Лучше устать пос" +
            "ле тренировки, чем жалеть, что пропустил её!|Сделай это ради себя, а не ради ког" +
            "о-то!|Ты заслуживаешь быть сильным и здоровым!|Жизнь – это движение, не стой на " +
            "месте!|Бегом к лучшей версии себя!\r\n")]
        public string MotivationPhrases {
            get {
                return ((string)(this["MotivationPhrases"]));
            }
            set {
                this["MotivationPhrases"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\r\n\t\t\"PullHour\": 22,\r\n\t\t\"PullMinute\": 0,\r\n\t\t\"GameDay\": 1,\r\n\t\t\"PullBeforeDay\": 3," +
            "\r\n\t\t\"GameStartHour\": 20,\r\n\t\t\"GameStartMinute\": 0,\r\n\t\t\"Location\": \"https://maps.e" +
            "xample.com/location1\",\r\n\t\t\"Title\": \"Понедельник, @GameDayName Волейбол в ЗАЛЕ(Ни" +
            "брас) с 8 до 10 вечера.\"\r\n\t},\r\n\t{\r\n\t\t\"PullHour\": 22,\r\n\t\t\"PullMinute\": 0,\r\n\t\t\"Gam" +
            "eDay\": 2,\r\n\t\t\"PullBeforeDay\": 3,\r\n\t\t\"GameStartHour\": 20,\r\n\t\t\"GameStartMinute\": 0" +
            ",\r\n\t\t\"Location\": \"https://maps.example.com/location2\",\r\n\t\t\"Title\": \"Вторник, @Ga" +
            "meDayName! Волейбол в ЗАЛЕ(Нибрас) с 8 до 10 вечера.\"\r\n\t},\r\n\t{\r\n\t\t\"PullHour\": 22" +
            ",\r\n\t\t\"PullMinute\": 0,\r\n\t\t\"GameDay\": 4,\r\n\t\t\"PullBeforeDay\": 3,\r\n\t\t\"GameStartHour\"" +
            ": 21,\r\n\t\t\"GameStartMinute\": 0,\r\n\t\t\"Location\": \"https://maps.example.com/location" +
            "2\",\r\n\t\t\"Title\": \"Четверг, @GameDayName! Волейбол в ЗАЛЕ(Нибрас) с 9 до 11 вечера" +
            ".\"\r\n\t},\r\n\t{\r\n\t\t\"PullHour\": 22,\r\n\t\t\"PullMinute\": 0,\r\n\t\t\"GameDay\": 5,\r\n\t\t\"PullBefo" +
            "reDay\": 3,\r\n\t\t\"GameStartHour\": 20,\r\n\t\t\"GameStartMinute\": 0,\r\n\t\t\"Location\": \"http" +
            "s://maps.example.com/location1\",\r\n\t\t\"Title\": \"Пятница, @GameDayName Волейбол в З" +
            "АЛЕ(Нибрас) с 8 до 10 вечера.\"\r\n\t},\r\n\t{\r\n\t\t\"PullHour\": 22,\r\n\t\t\"PullMinute\": 15,\r" +
            "\n\t\t\"GameDay\": 7,\r\n\t\t\"PullBeforeDay\": 3,\r\n\t\t\"GameStartHour\": 20,\r\n\t\t\"GameStartMin" +
            "ute\": 0,\r\n\t\t\"Location\": \"https://maps.example.com/location2\",\r\n\t\t\"Title\": \"Воскр" +
            "есенье, @GameDayName! Волейбол в ЗАЛЕ(Нибрас) с 8 до 10 вечера.\"\r\n\t},\r\n\t{\r\n\t\t\"Pu" +
            "llHour\": 22,\r\n\t\t\"PullMinute\": 0,\r\n\t\t\"GameDay\": 6,\r\n\t\t\"PullBeforeDay\": 3,\r\n\t\t\"Gam" +
            "eStartHour\": 19,\r\n\t\t\"GameStartMinute\": 0,\r\n\t\t\"ActiveGame\": false,\r\n\t\t\"Location\":" +
            " \"https://maps.example.com/location1\",\r\n\t\t\"Title\": \"Суббота, @GameDayName Волейб" +
            "ол в ЗАЛЕ(Нибрас) с 7 до 9 вечера.\"\r\n\t}\r\n\t]")]
        public string GamesJson {
            get {
                return ((string)(this["GamesJson"]));
            }
            set {
                this["GamesJson"] = value;
            }
        }
    }
}
