//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BallBotGui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1001912154644")]
        public string chatId {
            get {
                return ((string)(this["chatId"]));
            }
            set {
                this["chatId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Волейбол в ЗАЛЕ с 8 до 10 вечера.")]
        public string pollQuestion {
            get {
                return ((string)(this["pollQuestion"]));
            }
            set {
                this["pollQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Вторник. 20.00-22.00")]
        public string questTuesday {
            get {
                return ((string)(this["questTuesday"]));
            }
            set {
                this["questTuesday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Четверг 20.00-22.00")]
        public string questThursday {
            get {
                return ((string)(this["questThursday"]));
            }
            set {
                this["questThursday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Воскресенье 20.00-22.00")]
        public string questSunday {
            get {
                return ((string)(this["questSunday"]));
            }
            set {
                this["questSunday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Пропускаю. Но очень хочу играть.")]
        public string questSkip {
            get {
                return ((string)(this["questSkip"]));
            }
            set {
                this["questSkip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int pollDay {
            get {
                return ((int)(this["pollDay"]));
            }
            set {
                this["pollDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int pollHour {
            get {
                return ((int)(this["pollHour"]));
            }
            set {
                this["pollHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Играю!")]
        public string mainQuestion {
            get {
                return ((string)(this["mainQuestion"]));
            }
            set {
                this["mainQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1001645946649")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-912842250")]
        public string Setting1 {
            get {
                return ((string)(this["Setting1"]));
            }
            set {
                this["Setting1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5,6,2,4")]
        public string pollDayList {
            get {
                return ((string)(this["pollDayList"]));
            }
            set {
                this["pollDayList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int pollBeforeGame {
            get {
                return ((int)(this["pollBeforeGame"]));
            }
            set {
                this["pollBeforeGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{dayName} 19.00-21.00")]
        public string pollTitleTemplate {
            get {
                return ((string)(this["pollTitleTemplate"]));
            }
            set {
                this["pollTitleTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7109057711:AAHU_BqkQO3v9cElniVKIA44ABXrkGoMtDA")]
        public string curBotKey {
            get {
                return ((string)(this["curBotKey"]));
            }
            set {
                this["curBotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[
	{
		""PullHour"": 23,
		""PullMinute"": 0,
		""GameDay"": 1,
		""PullBeforeDay"": 3,
		""GameStartHour"": 20,
		""GameStartMinute"": 0,
		""Location"": ""https://maps.example.com/location1"",
		""Title"": ""Понедельник, @GameDayName Волейбол в ЗАЛЕ(Нибрас) с 8 до 10 вечера.""
	},
	{
		""PullHour"": 23,
		""PullMinute"": 0,
		""GameDay"": 2,
		""PullBeforeDay"": 3,
		""GameStartHour"": 20,
		""GameStartMinute"": 0,
		""Location"": ""https://maps.example.com/location2"",
		""Title"": ""Вторник, @GameDayName! Волейбол в ЗАЛЕ(Нибрас) с 8 до 10 вечера.""
	},
	{
		""PullHour"": 23,
		""PullMinute"": 0,
		""GameDay"": 4,
		""PullBeforeDay"": 3,
		""GameStartHour"": 21,
		""GameStartMinute"": 0,
		""Location"": ""https://maps.example.com/location2"",
		""Title"": ""Четрверг, @GameDayName! Волейбол в ЗАЛЕ(Нибрас) с 9 до 11 вечера.""
	},
	{
		""PullHour"": 23,
		""PullMinute"": 0,
		""GameDay"": 5,
		""PullBeforeDay"": 3,
		""GameStartHour"": 20,
		""GameStartMinute"": 0,
		""Location"": ""https://maps.example.com/location1"",
		""Title"": ""Пятница, @GameDayName Волейбол в ЗАЛЕ(Нибрас) с 8 до 10 вечера.""
	},
	{
		""PullHour"": 23,
		""PullMinute"": 0,
		""GameDay"": 7,
		""PullBeforeDay"": 3,
		""GameStartHour"": 20,
		""GameStartMinute"": 0,
		""Location"": ""https://maps.example.com/location2"",
		""Title"": ""Воскресенье, @GameDayName! Волейбол в ЗАЛЕ(Нибрас) с 8 до 10 вечера.""
	}
]")]
        public string GamesJson {
            get {
                return ((string)(this["GamesJson"]));
            }
            set {
                this["GamesJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Приветствуем, @Player!\r\n - Мы вам рады!\r\n - Ответы на вопросы Где? Когда? Как зап" +
            "исаться? тут: https://t.me/c/1645946649/4774\r\n - Обязательно напишите о своем ур" +
            "овне игры.\r\n - Все текущие игры в закрепах")]
        public string inviteMessage {
            get {
                return ((string)(this["inviteMessage"]));
            }
            set {
                this["inviteMessage"] = value;
            }
        }
    }
}
